// Actions related to tenants
export const SET_TENANT_PROFILE = 'SET_TENANT_PROFILE'
export const CONNECT_WEBSOCKETS = 'CONNECT_WEBSOCKETS'
export const INITIATE_POUCHDB = 'INITIATE_POUCHDB'

// Actions related to selections
export const SELECT_BUILDING = 'SELECT_BUILDING'
export const SELECT_LANDLORD = 'SELECT_LANDLORD'

// Actions related to messaging
export const SEND_MESSAGE = 'SEND_MESSAGE'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const SELECT_CHAT_BUILDING = 'SELECT_CHAT_BUILDING'
export const SELECT_CHAT_LANDLORD = 'SELECT_CHAT_LANDLORD'
export const SELECT_CHAT_CHANNEL = 'SELECT_CHAT_CHANNEL'
export const BACK_TO_CHAT_CHANNELS = 'BACK_TO_CHAT_CHANNELS'
